import Head from "next/head";
import Image from "next/image";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.css";
import {useEffect, useState} from "react";
import axios from "axios";
import {useCharacters} from "@/assets/hooks/useCharacters";
import {CharacterCard} from "@/components/CharacterCard/CharacterCard";

const inter = Inter({subsets: ["latin"]});

export default function Characters() {
    const characters = useCharacters()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                {characters&&characters.map(character=>(
                    <CharacterCard id={character.id} name={character.name} image={character.image} key={character.id}/>
                ))}
            </main>
        </>
    );
}
//types
